### ISSUE TITLE
提示绘制图片 i.drawImage is no a function

### ISSUE THREAD

**Issue by sichaofei** [wechat-miniprogram/lottie-miniprogram#10]
VM902:1 thirdScriptError
i.drawImage is not a function
TypeError: i.drawImage is not a function

这怎么回事  图片的问题吗？？

**Comment by seasonhuang** [comment]
请提供个代码片段看看

**Comment by mintsoda** [comment]
遇到相同的问题，请问解决了吗

**Comment by seasonhuang** [comment]
@mintsoda 请提供个代码片段看看

**Comment by jumpDuckEgg** [comment]
同样的问题：
`<canvas id="canvas" type="2d"></canvas>`
`wx.createSelectorQuery().select('#canvas').node(res => {
			const canvas = res.node;
			const context = canvas.getContext('2d');
				lottie.setup(canvas);
				lottie.loadAnimation({
					loop: true,
					autoplay: true,
					path: 'https://static-files.mama.cn/wxapp/baobaojilu/lottie/p2/p2.json',
					rendererSettings:{
						context
					}
				})
			}).exec()`

**Comment by seasonhuang** [comment]
这个是因为该 lottie json 尝试动态创建 canvas，但小程序不支持动态创建组件，建议使用不动态创建 canvas 的 lottie 资源，或者保持图片的原始宽高与 JSON 描述的一致，避免需要对图片处理

**Comment by jumpDuckEgg** [comment]
> 这个是因为该 lottie json 尝试动态创建 canvas，但小程序不支持动态创建组件，建议使用不动态创建 canvas 的 lottie 资源，或者保持图片的原始宽高与 JSON 描述的一致，避免需要对图片处理

调整了一下，工具可以跑了，但是预览没东西，真机报的是已知的不支持调试的问题
