### ISSUE TITLE
多个页面都加载lottie，跳转后出现问题

### ISSUE THREAD

**Issue by kongxiuzhe** [wechat-miniprogram/lottie-miniprogram#16]
发现lottie-miniprogram的bug，如果2个页面都有canvas进行lottie播放，第一个页面跳转第二个页面后返回，第一个页面的lottie动画就停止了，重新调用loadAnimation或play都无效

**Comment by Marcowutt** [comment]
可以看下这个回答： https://developers.weixin.qq.com/community/develop/doc/000c6c7330ce30571a1a4537556c00

**Comment by Marcowutt** [comment]
> 发现lottie-miniprogram的bug，如果2个页面都有canvas进行lottie播放，第一个页面跳转第二个页面后返回，第一个页面的lottie动画就停止了，重新调用loadAnimation或play都无效

看下这个回答：https://developers.weixin.qq.com/community/develop/doc/000c6c7330ce30571a1a4537556c00

**Comment by Marcowutt** [comment]
> 发现lottie-miniprogram的bug，如果2个页面都有canvas进行lottie播放，第一个页面跳转第二个页面后返回，第一个页面的lottie动画就停止了，重新调用loadAnimation或play都无效

试试这个问题下的回答的方法：https://developers.weixin.qq.com/community/develop/doc/000c6c7330ce30571a1a4537556c00

**Comment by seasonhuang** [comment]
麻烦提供一下代码片段看看

**Comment by fuchenxu2008** [comment]
我也遇到了这个问题，刷新小程序几次就不动了

**Comment by seasonhuang** [comment]
> 我也遇到了这个问题，刷新小程序几次就不动了

@fuchenxu2008 请提供下代码片段

**Comment by kongxiuzhe** [comment]
> 麻烦提供一下代码片段看看

@seasonhuang 都不需要提供代码片段，拿官方demo复制一个相同的页面，然后做跳转返回就能复现，只能通过修改组件源码解决

**Comment by Amandesu** [comment]
@kongxiuzhe 如何修改组件源码哈

**Comment by seasonhuang** [comment]
已修复，在页面 onUnload 时，调用 destroy 方法即可

**Comment by tanhuaendd01** [comment]
还是会出现这个问题，当动画正在执行的时候返回重新进入，无法再加载动画

**Comment by seasonhuang** [comment]
@dd01tanhuaen 播放另一个动画时，先把上一个动画 destroy 掉试试。如还有问题，请提供代码片段

**Comment by kongxiuzhe** [comment]
> @kongxiuzhe 如何修改组件源码哈

删除miniprogram_npm/lottie-miniprogram/index.js的e.requestAnimationFrame=t.requestAnimationFrame.bind(t),e.cancelAnimationFrame=t.cancelAnimationFrame.bind(t)

**Comment by kongxiuzhe** [comment]
> @kongxiuzhe 如何修改组件源码哈

@Amandesu 删除miniprogram_npm/lottie-miniprogram/index.js的e.requestAnimationFrame=t.requestAnimationFrame.bind(t),e.cancelAnimationFrame=t.cancelAnimationFrame.bind(t)
