### ISSUE TITLE
使用这个库加载lottie的json文件，TypeError: eval is not a function

### ISSUE THREAD

**Issue by EricHan0723** [wechat-miniprogram/lottie-miniprogram#2]
![微信截图_20190905135955](https://user-images.githubusercontent.com/5415578/64315740-7e018500-cfe5-11e9-92b0-a5a5a94085ac.png)
使用样例的js没问题，请问样例是从哪里找的呢？我在lottiefile里只能找到json文件

**Comment by EricHan0723** [comment]
使用的lottie链接在这里https://lottiefiles.com/8990-graficos-aleatorios

**Comment by seasonhuang** [comment]
这个用到了 expression
由于小程序本身不支持动态执行脚本，因此 lottie 的 expression 功能也是不支持的。

**Comment by kingzez** [comment]
> 这个用到了 expression
> 由于小程序本身不支持动态执行脚本，因此 lottie 的 expression 功能也是不支持的。

如何区分是否用到了 expression？

**Comment by ultravires** [comment]
> 这个用到了 expression 由于小程序本身不支持动态执行脚本，因此 lottie 的 expression 功能也是不支持的。

请问解决方案是什么？能提供 eval 函数设置吗。我们自实现一个 _eval()。然后可以传入

{
eval: _eval
}

使得expression能够被_eval执行

**Comment by wingyippp** [comment]
@seasonhuang 有没有工具把一个lottie动画干掉 expression，让它能支持在小程序上运行？

**Comment by sunjunjie1314520** [comment]
> ![微信截图_20190905135955](https://user-images.githubusercontent.com/5415578/64315740-7e018500-cfe5-11e9-92b0-a5a5a94085ac.png) 使用样例的js没问题，请问样例是从哪里找的呢？我在lottiefile里只能找到json文件

你这个是怎么解决的，？
![image](https://github.com/wechat-miniprogram/lottie-miniprogram/assets/34414647/a317e681-e4f3-4492-837c-4742a3943943)
我也出现这种问题了

**Comment by Liqiankun** [comment]
@seasonhuang 请问解决没？

**Comment by sunjunjie1314520** [comment]
文件已收到！谢谢！

**Comment by Liqiankun** [comment]
@seasonhuang 我的意思是怎么解决的，我也有这个问题。请教。
