### ISSUE TITLE
重新加载页面时，没有动画

### ISSUE THREAD

**Issue by jiazil** [wechat-miniprogram/lottie-miniprogram#20]

**Comment by seasonhuang** [comment]
@jiazil 请提供个代码片段看看

**Comment by tanhuaendd01** [comment]
https://developers.weixin.qq.com/s/NlMHfxmr7rjD

**Comment by tanhuaendd01** [comment]
真机预览

在动画过程中，后退，然后重新进入可以重现改问题

**Comment by Sanford284** [comment]
1. 进入有lottie动画的页面
2. 返回上一页或者navigateTo其他页面
3. 再进入有lottie动画的页面
lottie动画失效，不会触发complete事件。 

并且，destroy API 在小程序使用报错。

**Comment by seasonhuang** [comment]
@yuwanlin 修复了，更新一下版本看看

**Comment by xinghui** [comment]
v1.0.10复现
