### ISSUE TITLE
模拟器显示正常，真机上显示大小是实际的一般，而且分辨率很低，什么原因呢？

### ISSUE THREAD

**Issue by jiji262** [wechat-miniprogram/lottie-miniprogram#23]
模拟器上效果：
![image](https://user-images.githubusercontent.com/168751/94102596-1377ed00-fe65-11ea-8c71-546bce77461a.png)

真机效果：
![image](https://user-images.githubusercontent.com/168751/94102630-22f73600-fe65-11ea-86e0-9d424eb50791.png)

**Comment by DBliuchengjie** [comment]
我也遇到了这个问题，感觉是需要吧json文件需要的图片资源尺寸都放大一倍，可能真机上才能不模糊

**Comment by DBliuchengjie** [comment]
我知道原因了，借用了一下你的图片，写了篇文章：https://juejin.im/post/6885226710623764488 。 可以解决此问题。

**Comment by kukudeliu** [comment]
总结了网上的文章；
http://t.csdn.cn/6De5A
