### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by 2125zyrc** [wechat-miniprogram/lottie-miniprogram#24]
重复刷新小程序页面  大概重复20次左右  会出现小程序内存泄漏的提醒

**Comment by seasonhuang** [comment]
@2125zyrc 有没有代码片段？正常可能需要在页面销毁时释放

**Comment by Zenfeder** [comment]
@2125zyrc  请问内存泄漏的问题有解决方案么？

**Comment by ahaow** [comment]
请问怎么解决的呢？

**Comment by 2125zyrc** [comment]
> 请问怎么解决的呢？

现在依旧还有这个问题吗 ？
