### ISSUE TITLE
使用时，图片会特别模糊，同样的json和资源文件在web下面使用svg渲染没有问题

### ISSUE THREAD

**Issue by bigkrys** [wechat-miniprogram/lottie-miniprogram#26]
使用lottie-web在web下面渲染方式选择svg的时候，渲染出来的动画高清的，但是在小程序中，使用lottie-miniprogram渲染方式是canvas的时候，渲染出来的图片会特别模糊。
下面是使用lottie-web在html中使用svg渲染的效果。
![image](https://user-images.githubusercontent.com/17899020/102178873-27ba0c00-3ee1-11eb-85ce-3c02e7551ab4.png)

下面是在微信小程序中，使用lottie-miniprogram渲染的效果
![image](https://user-images.githubusercontent.com/17899020/102178705-d742ae80-3ee0-11eb-85f6-ad78dd6d8433.png)

**Comment by peter-jerry-ye** [comment]
根据[这篇文章](https://www.mdeditor.tw/pl/puLX)，你需要设置canvas的大小以及分辨率

**Comment by bigkrys** [comment]
> 根据[这篇文章](https://www.mdeditor.tw/pl/puLX)，你需要设置canvas的大小以及分辨率

谢谢已经解决了

**Comment by kukudeliu** [comment]
楼上链接不可用了；
http://t.csdn.cn/6De5A
