### ISSUE TITLE
希望可以调节requestAnimationFrame的timeout

### ISSUE THREAD

**Issue by FireTable** [wechat-miniprogram/lottie-miniprogram#28]
查看源码: lottie-miniprogram/src/adapter/index.js 

```
requestAnimationFrame(cb) {
    setTimeout(() => {
      typeof cb === 'function' && cb(Date.now())
    }, 16)
  },
```

发现timeout: 16, 以每秒60+帧绘制

**希望这个16可以作为参数配置化, 或者以fps的方式来限制绘制帧 => timeout = 1000/fps**

**原因: 目前小程序使用lottie, 经常内存泄漏, 如果在loadAnimation的时候可以指定, 那么应该可以控制一下性能问题?**

**Comment by seasonhuang** [comment]
@FireTable 这个配置跟内存泄漏关系应该不大，正常应该是在页面/动画销毁时 lottie 内部去 cancelAnimationFrame

**Comment by seasonhuang** [comment]
@FireTable 内存泄漏的 case 可以提供个代码片段看看  https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
