### ISSUE TITLE
json中引用图片就会报错，请问有解决方案吗？

### ISSUE THREAD

**Issue by Wuge-Ran** [wechat-miniprogram/lottie-miniprogram#29]
![image](https://user-images.githubusercontent.com/37544649/113398633-80021480-93d1-11eb-87b6-43dff094c5b0.png)
![image](https://user-images.githubusercontent.com/37544649/113398761-ad4ec280-93d1-11eb-9881-f0f47e3f8da9.png)

**Comment by bobsam** [comment]
同遇到问题

**Comment by bobsam** [comment]
用这个吧：https://github.com/landn172/lottie-miniapp 亲测可用

**Comment by JayEdver** [comment]
这个是因为lottie中图片的尺寸必须与json中的配置一致。比如w: 1125, h:2436 ，那你就只能用1125*2436分辨率的图片

**Comment by Genuifx** [comment]
无解，
基础库大于2.11.0的，可以让设计师导出的时候把图片塞到json里面

另外就是相对路径的图片是支持的，保证你的小程序文件夹里面的路径正确就行
