### ISSUE TITLE
发现 Lottie 动态创建 canvas 组件，但小程序不支持动态创建组件

### ISSUE THREAD

**Issue by wang90** [wechat-miniprogram/lottie-miniprogram#30]
项目中集成插件，在编辑器中发现提示“ Lottie 动态创建 canvas 组件，但小程序不支持动态创建组件”，动画可以在测试跑通，但是上线后会有很多关于canvas报错，但是不能定位具体问题，不知道是不是编辑器提示这个错误的原因。

**Comment by kelaocai** [comment]
基础库2.23.3有这个问题，2.19.6没问题
