### ISSUE TITLE
性能很差，大概7个canvas就会造成小程序奔溃，IOS和安卓都会出现

### ISSUE THREAD

**Issue by JokerLoLgrey** [wechat-miniprogram/lottie-miniprogram#34]
使用了7个canvas，页面会出现卡顿，严重的情况会出现小程序奔溃，请问有什么解决办法吗

**Comment by Genuifx** [comment]
7个canvas，你就是不跑lottie 自己画动画也会卡的，不应该减少点吗

**Comment by JokerLoLgrey** [comment]
> 7个canvas，你就是不跑lottie 自己画动画也会卡的，不应该减少点吗

h5还好，但是canvas感觉已经到达性能极限了，直接报内存不足，现在已经换gif方案了
