### ISSUE TITLE
使用webpack重新打包报错

### ISSUE THREAD

**Issue by amu507** [wechat-miniprogram/lottie-miniprogram#37]
1. 从github上下载最新版本的"lottie-miniprogram"并解压
2. 在解压的文件夹下执行"npm install"
3. 执行"npm run build"以及"webpack"均报错
<img width="906" alt="image" src="https://user-images.githubusercontent.com/26849220/204702329-afd90adc-e0fd-40f5-85f4-a9ebc07594bc.png">
<img width="706" alt="image" src="https://user-images.githubusercontent.com/26849220/204702222-6019500e-5fcf-4fd4-91af-94fab890711b.png">

**Comment by clydee-geng** [comment]
都没人维护了，kpi项目
