### ISSUE TITLE
使用带图片资源的文件在真机上会报错

### ISSUE THREAD

**Issue by httIsHere** [wechat-miniprogram/lottie-miniprogram#4]
![image](https://user-images.githubusercontent.com/18690331/65232973-aa98bf00-db04-11e9-8627-1283c2f6c2ee.png)

**Comment by seasonhuang** [comment]
能否提供一下 json 文件

**Comment by httIsHere** [comment]
[json文件](https://assets-cdn.lanqb.com/manual-box/mp/coin.json)

**Comment by seasonhuang** [comment]
是因为小程序的 canvas 的 createImage 接口还不支持 base64，把 base64 替换成网络路径试试
