### ISSUE TITLE
能否修改canvas渲染之后元素的位置还有大小呢

### ISSUE THREAD

**Issue by zsbox** [wechat-miniprogram/lottie-miniprogram#6]
当cavas渲染完成以后动画元素也就渲染完成了，假如我用同一个canvas渲染其他当元素
很尴尬，动画元素当位置和大小无法修改，其他元素也就无法渲染了，会重叠，请问修改哪里

**Comment by seasonhuang** [comment]
不是很理解，是指重新渲染一帧画面，和上一帧画面重叠？那你需要先清空 canvas 再画下一帧

**Comment by ocsxxi** [comment]
我认为他想说的是，在使用了ctx.scale(dpr, dpr)后，虽然在ios端(我只测了ios端)上的显示位置正常，但是在微信开发者工具上的渲染会向上偏移原canvas一半的距离。

![图片](https://user-images.githubusercontent.com/44924994/173977754-717ecac2-2ea2-4aeb-a6d8-ebb9958c80cb.png)

调试基础库：2.24.5
lottie版本：lottie-miniprogram@1.0.12
